version: 2
updates:
  # Update GitHub actions
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels:
      - dependencies
  # Update Go dependencies
  - directory: /
    package-ecosystem: gomod
    schedule:
      interval: weekly
    commit-message:
      prefix: build(go)
    labels:
      - dependencies
    ignore:
    - dependency-name: 'github.com/caddyserver/caddy/v2'
  # Update Docker base images
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly
    commit-message:
      prefix: build(docker)
    labels:
      - dependencies