name: Build and test
on: push

jobs:
  build:
    name: Build and test image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    steps:      
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dev.Dockerfile
          platforms: linux/${{ matrix.arch }}
          load: true
          tags: stable-test

      - name: Test
        run: |
          docker run --rm stable-test caddy stop
  