name: Release

on:
  push:
    tags:
      - "v*"

env:
  CADDY_VERSION: 2.6.4

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Get the tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/v/}

    # - name: Set up QEMU
    #   run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image identity
      id: image_id
      run: echo ::set-output name=ID::${GITHUB_REPOSITORY,,}

    - name: Publish to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        build-args: |
          CADDY_VERSION=${{ env.CADDY_VERSION }}
          TAG=${{ steps.get_tag.outputs.TAG }}
        context: .
        push: true
        tags: |
          ghcr.io/${{ steps.image_id.outputs.ID }}:${{ steps.get_tag.outputs.TAG }}-caddy-${{ env.CADDY_VERSION }}