name: Release

on:
  push:
    tags:
      - "v*"

env:
  CADDY_VERSION: 2.7.5

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Get the tag
      id: get_tag
      run: |
        echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    # - name: Set up QEMU
    #   run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          ${{ steps.get_tag.outputs.TAG }}-caddy-${{ env.CADDY_VERSION }},
          ${{ steps.get_tag.outputs.TAG }}
          latest

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          CADDY_VERSION=${{ env.CADDY_VERSION }}
          TAG=${{ steps.get_tag.outputs.TAG }}
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}